{"name": "Проверка появления ошибки при получении заказов  неавторизованным пользователем", "status": "passed", "start": 1725891349394, "stop": 1725891349637, "uuid": "92477602-c3a4-4864-94c7-3c68eb70c525", "historyId": "64da9323935f466100b879244f06b4e3", "testCaseId": "64da9323935f466100b879244f06b4e3", "fullName": "tests.test_get_user_order.TestGetUserOrder#test_get_user_order_without_auth_show_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_user_order"}, {"name": "subSuite", "value": "TestGetUserOrder"}, {"name": "host", "value": "Nightingales-MacBook-Air.local"}, {"name": "thread", "value": "936-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_user_order"}]}