{"name": "Проверка появления ошибки при авторизации под несуществующим пользователем", "status": "passed", "start": 1725891350605, "stop": 1725891351232, "uuid": "d4935ac1-b8c8-40cc-b396-2e9e684dd6e6", "historyId": "4fe2b928257268ff98fae7743e7456f6", "testCaseId": "4fe2b928257268ff98fae7743e7456f6", "fullName": "tests.test_login_user.TestLoginUser#test_login_wrong_data_shows_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "Nightingales-MacBook-Air.local"}, {"name": "thread", "value": "936-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}