{"name": "Проверка появления ошибки при создании уже зарегистрированного пользователя", "status": "passed", "start": 1725891346848, "stop": 1725891347064, "uuid": "e8214ada-d74e-4e72-aa9f-70dc0f931594", "historyId": "9ef1a4c659b5c04a8b9f92ac0d223aeb", "testCaseId": "9ef1a4c659b5c04a8b9f92ac0d223aeb", "fullName": "tests.test_create_user.TestCreateUser#test_create_same_user_shows_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "Nightingales-MacBook-Air.local"}, {"name": "thread", "value": "936-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}